// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* sources/WSListenator.h
   Generated by wsdl2h 2.8.44 from wsdl/WSListenator.wsdl and typemap.dat
   2017-03-27 08:06:00 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on sources/WSListenator.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stl.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/

#import "stl.h"	// enable STL containers when used (option -s removes STL dependency)

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

tempuri = "http://tempuri.org/"
ns1 = "urn:WSPlayerIntf"

*/

#define SOAP_NAMESPACE_OF_ns1	"urn:WSPlayerIntf"
//gsoap ns1   schema namespace:	urn:WSPlayerIntf
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class ns1__RequestType.
class ns1__RequestType;

//  Forward declaration of class ns1__ResponseType.
class ns1__ResponseType;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:WSPlayerIntf                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:WSPlayerIntf                                                         *
 *                                                                            *
\******************************************************************************/

/// @brief "urn:WSPlayerIntf":RequestType is a complexType.
///
/// class ns1__RequestType operations:
/// - ns1__RequestType* soap_new_ns1__RequestType(soap*) allocate and default initialize
/// - ns1__RequestType* soap_new_ns1__RequestType(soap*, int num) allocate array and default initialize values
/// - ns1__RequestType* soap_new_req_ns1__RequestType(soap*, ...) allocate, set required members
/// - ns1__RequestType* soap_new_set_ns1__RequestType(soap*, ...) allocate, set all public members
/// - ns1__RequestType::soap_default(soap*) default initialize members
/// - int soap_read_ns1__RequestType(soap*, ns1__RequestType*) deserialize from a stream
/// - int soap_write_ns1__RequestType(soap*, ns1__RequestType*) serialize to a stream
/// - ns1__RequestType* ns1__RequestType::soap_dup(soap*) returns deep copy of ns1__RequestType, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__RequestType::soap_del() deep deletes ns1__RequestType data members, use only after ns1__RequestType::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__RequestType
{ public:
/// Element "nomChanson" of XSD type xs:string.
    std::string                          nomChanson                     1;	///< Required element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "urn:WSPlayerIntf":ResponseType is a complexType.
///
/// class ns1__ResponseType operations:
/// - ns1__ResponseType* soap_new_ns1__ResponseType(soap*) allocate and default initialize
/// - ns1__ResponseType* soap_new_ns1__ResponseType(soap*, int num) allocate array and default initialize values
/// - ns1__ResponseType* soap_new_req_ns1__ResponseType(soap*, ...) allocate, set required members
/// - ns1__ResponseType* soap_new_set_ns1__ResponseType(soap*, ...) allocate, set all public members
/// - ns1__ResponseType::soap_default(soap*) default initialize members
/// - int soap_read_ns1__ResponseType(soap*, ns1__ResponseType*) deserialize from a stream
/// - int soap_write_ns1__ResponseType(soap*, ns1__ResponseType*) serialize to a stream
/// - ns1__ResponseType* ns1__ResponseType::soap_dup(soap*) returns deep copy of ns1__ResponseType, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__ResponseType::soap_del() deep deletes ns1__ResponseType data members, use only after ns1__ResponseType::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__ResponseType
{ public:
/// Element "url" of XSD type xs:string.
    std::string                          url                            1;	///< Required element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:WSPlayerIntf                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:WSPlayerIntf                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	IWSPlayerbinding 
//gsoap ns2  service type:	IWSPlayer 
//gsoap ns2  service port:	http://localhost:8080/soap/IWSPlayer 
//gsoap ns2  service namespace:	urn:WSPlayerIntf-IWSPlayer 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage IWSPlayerservice Definitions

@section IWSPlayerservice_bindings Service Bindings

  - @ref IWSPlayerbinding

@section IWSPlayerservice_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page IWSPlayerbinding Binding "IWSPlayerbinding"

@section IWSPlayerbinding_operations Operations of Binding "IWSPlayerbinding"

  - @ref ns2__jouerChanson

@section IWSPlayerbinding_ports Default endpoints of Binding "IWSPlayerbinding"

  - http://localhost:8080/soap/IWSPlayer

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   IWSPlayerbinding                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__jouerChanson                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__jouerChansonResponse" of operation "ns2__jouerChanson".
struct ns2__jouerChansonResponse
{
    ns1__ResponseType*                  :return_;	///< Output parameter, : unqualified name as per RPC encoding
};

/** Operation "ns2__jouerChanson" of service binding "IWSPlayerbinding".

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://localhost:8080/soap/IWSPlayer

  - Default SOAP action or REST location path:
    - "urn:WSPlayerIntf-IWSPlayer#jouerChanson"

  - Addressing input action: "urn:WSPlayerIntf-IWSPlayer#jouerChanson"

  - Addressing output action: "urn:WSPlayerIntf-IWSPlayer#jouerChansonResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__jouerChanson(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__RequestType*                   Request,
    // output parameters:
    struct ns2__jouerChansonResponse&
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__jouerChanson(
    struct soap *soap,
    // input parameters:
    ns1__RequestType*                   Request,
    // output parameters:
    struct ns2__jouerChansonResponse&
  );
@endcode

C++ proxy class (defined in soapIWSPlayerbindingProxy.h generated with soapcpp2):
@code
  class IWSPlayerbindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapIWSPlayerbindingService.h generated with soapcpp2):
@code
  class IWSPlayerbindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns2  service method-protocol:	jouerChanson SOAP
//gsoap ns2  service method-style:	jouerChanson rpc
//gsoap ns2  service method-encoding:	jouerChanson http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	jouerChanson urn:WSPlayerIntf-IWSPlayer#jouerChanson
//gsoap ns2  service method-output-action:	jouerChanson urn:WSPlayerIntf-IWSPlayer#jouerChansonResponse
int ns2__jouerChanson(
    ns1__RequestType*                   :Request,	///< Input parameter, : unqualified name as per RPC encoding
    struct ns2__jouerChansonResponse   &	///< Output response struct parameter
);

/**

@page IWSPlayerbinding Binding "IWSPlayerbinding"

@section IWSPlayerbinding_policy_enablers Policy Enablers of Binding "IWSPlayerbinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "urn:WSPlayerIntf"

*/

/* End of sources/WSListenator.h */
